//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChipMongWebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRetailer
    {
        public int retl_RetailerID { get; set; }
        public string retl_Name { get; set; }
        public string retl_Address { get; set; }
        public Nullable<int> retl_Deleted { get; set; }
        public Nullable<int> retl_CustomerID { get; set; }
        public string retl_Code { get; set; }
        public string retl_Province { get; set; }
        public string retl_District { get; set; }
        public string retl_Phone { get; set; }
        public string retl_Phone2 { get; set; }
    }
}
