//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChipMongWebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSaleOrder
    {
        public int id { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public string code { get; set; }
        public Nullable<int> deleted { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<decimal> total { get; set; }
        public string status { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> retailerID { get; set; }
        public Nullable<int> preOrderID { get; set; }
        public Nullable<int> sourceOfSupplyID { get; set; }
        public Nullable<System.DateTime> requiredDate { get; set; }
        public string pickUp { get; set; }
        public string slor_TruckNo { get; set; }
        public Nullable<int> slor_UserID { get; set; }
        public string slor_DocNo { get; set; }
        public string slor_ShipmentNo { get; set; }
        public Nullable<int> slor_LockBy { get; set; }
        public Nullable<System.DateTime> slor_LockOn { get; set; }
        public string slor_TruckDriverPhoneNo { get; set; }
        public string slor_TransportZone { get; set; }
        public string slor_SONo { get; set; }
        public string slor_ShipConidtion { get; set; }
        public Nullable<System.DateTime> slor_TimeUpdateStatus { get; set; }
        public Nullable<int> slor_Status1By { get; set; }
        public Nullable<System.DateTime> slor_Status1Date { get; set; }
        public Nullable<System.DateTime> slor_Status1Send { get; set; }
        public Nullable<int> slor_Status2By { get; set; }
        public Nullable<System.DateTime> slor_Status2Date { get; set; }
        public Nullable<System.DateTime> slor_Status2Send { get; set; }
        public Nullable<int> slor_Status3By { get; set; }
        public Nullable<System.DateTime> slor_Status3Date { get; set; }
        public Nullable<System.DateTime> slor_Status3Send { get; set; }
        public Nullable<int> slor_Status4By { get; set; }
        public Nullable<System.DateTime> slor_Status4Date { get; set; }
        public Nullable<System.DateTime> slor_Status4Send { get; set; }
        public Nullable<int> slor_Status5By { get; set; }
        public Nullable<System.DateTime> slor_Status5Date { get; set; }
        public Nullable<System.DateTime> slor_Status5Send { get; set; }
        public Nullable<int> slor_Status6By { get; set; }
        public Nullable<System.DateTime> slor_Status6Date { get; set; }
        public Nullable<System.DateTime> slor_Status6Send { get; set; }
        public Nullable<System.DateTime> slor_SendDate { get; set; }
    }
}
