//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChipMongWebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vExportSaleOrder
    {
        public int slor_SaleOrderID { get; set; }
        public Nullable<System.DateTime> slor_CreatedDate { get; set; }
        public Nullable<int> slor_CreatedBy { get; set; }
        public Nullable<System.DateTime> slor_UpdatedDate { get; set; }
        public Nullable<int> slor_UpdatedBy { get; set; }
        public string slor_Code { get; set; }
        public Nullable<int> slor_Deleted { get; set; }
        public Nullable<int> slor_CustomerID { get; set; }
        public Nullable<decimal> slor_Total { get; set; }
        public string slor_Status { get; set; }
        public string slor_Remarks { get; set; }
        public Nullable<System.DateTime> slor_Date { get; set; }
        public Nullable<int> slor_RetailerID { get; set; }
        public Nullable<int> slor_PreOrderID { get; set; }
        public Nullable<int> slor_SourceOfSupply { get; set; }
        public Nullable<System.DateTime> slor_RequiredDate { get; set; }
        public string slor_PickUp { get; set; }
        public string slor_TruckNo { get; set; }
        public Nullable<int> slor_UserID { get; set; }
        public Nullable<int> retl_RetailerID { get; set; }
        public string retl_Name { get; set; }
        public string retl_Address { get; set; }
        public Nullable<int> retl_Deleted { get; set; }
        public Nullable<int> retl_CustomerID { get; set; }
        public string retl_Code { get; set; }
        public string retl_Province { get; set; }
        public string retl_District { get; set; }
        public string retl_Phone { get; set; }
        public string retl_Phone2 { get; set; }
        public Nullable<int> scsp_SourceOfSupplyID { get; set; }
        public string scsp_Name { get; set; }
        public Nullable<int> scsp_Deleted { get; set; }
        public Nullable<int> cust_CustomerID { get; set; }
        public Nullable<System.DateTime> cust_CreatedDate { get; set; }
        public Nullable<int> cust_CreatedBy { get; set; }
        public Nullable<System.DateTime> cust_UpdatedDate { get; set; }
        public Nullable<int> cust_UpdatedBy { get; set; }
        public string cust_Code { get; set; }
        public string cust_FirstName { get; set; }
        public string cust_LastName { get; set; }
        public string cust_Phone1 { get; set; }
        public string cust_Phone2 { get; set; }
        public string cust_Password { get; set; }
        public string cust_Token { get; set; }
        public string cust_Email { get; set; }
        public string cust_Address { get; set; }
        public Nullable<int> cust_Deleted { get; set; }
        public string cust_LineID { get; set; }
        public string cust_LastCommand { get; set; }
        public string cust_LastCommandValue { get; set; }
        public string cust_LastCommandValue2 { get; set; }
        public string cust_Lang { get; set; }
        public string cust_LastCommandValue3 { get; set; }
        public Nullable<int> cust_EditPOID { get; set; }
        public Nullable<int> cust_EditSOID { get; set; }
        public Nullable<int> cust_cPage { get; set; }
        public Nullable<int> cust_UserID { get; set; }
        public string slor_DocNo { get; set; }
        public string slor_ShipmentNo { get; set; }
        public Nullable<int> slor_LockBy { get; set; }
        public Nullable<System.DateTime> slor_LockOn { get; set; }
        public string slor_TruckDriverPhoneNo { get; set; }
        public string slor_TransportZone { get; set; }
        public string slor_SONo { get; set; }
        public string slor_ShipConidtion { get; set; }
        public Nullable<System.DateTime> slor_TimeUpdateStatus { get; set; }
        public Nullable<int> slor_Status1By { get; set; }
        public Nullable<System.DateTime> slor_Status1Date { get; set; }
        public Nullable<System.DateTime> slor_Status1Send { get; set; }
        public Nullable<int> slor_Status2By { get; set; }
        public Nullable<System.DateTime> slor_Status2Date { get; set; }
        public Nullable<System.DateTime> slor_Status2Send { get; set; }
        public Nullable<int> slor_Status3By { get; set; }
        public Nullable<System.DateTime> slor_Status3Date { get; set; }
        public Nullable<System.DateTime> slor_Status3Send { get; set; }
        public Nullable<int> slor_Status4By { get; set; }
        public Nullable<System.DateTime> slor_Status4Date { get; set; }
        public Nullable<System.DateTime> slor_Status4Send { get; set; }
        public Nullable<int> slor_Status5By { get; set; }
        public Nullable<System.DateTime> slor_Status5Date { get; set; }
        public Nullable<System.DateTime> slor_Status5Send { get; set; }
        public Nullable<int> slor_Status6By { get; set; }
        public Nullable<System.DateTime> slor_Status6Date { get; set; }
        public Nullable<System.DateTime> slor_Status6Send { get; set; }
        public Nullable<System.DateTime> slor_SendDate { get; set; }
        public string user1 { get; set; }
        public string user2 { get; set; }
        public string user3 { get; set; }
        public string user4 { get; set; }
        public string user5 { get; set; }
        public string user6 { get; set; }
        public string editBy { get; set; }
        public Nullable<int> sloi_SaleOrderItemID { get; set; }
        public Nullable<System.DateTime> sloi_CreatedDate { get; set; }
        public Nullable<int> sloi_CreatedBy { get; set; }
        public Nullable<System.DateTime> sloi_UpdatedDate { get; set; }
        public Nullable<int> sloi_UpdatedBy { get; set; }
        public string sloi_Code { get; set; }
        public Nullable<int> sloi_Deleted { get; set; }
        public Nullable<decimal> sloi_Quantity { get; set; }
        public Nullable<decimal> sloi_Price { get; set; }
        public Nullable<decimal> sloi_Total { get; set; }
        public Nullable<int> sloi_SaloeOrderID { get; set; }
        public Nullable<int> sloi_ItemID { get; set; }
        public Nullable<int> item_ItemID { get; set; }
        public Nullable<System.DateTime> item_CreatedDate { get; set; }
        public Nullable<int> item_CreatedBy { get; set; }
        public Nullable<System.DateTime> item_UpdatedDate { get; set; }
        public Nullable<int> item_UpdatedBy { get; set; }
        public string item_Code { get; set; }
        public Nullable<int> item_Deleted { get; set; }
        public Nullable<decimal> item_Cost { get; set; }
        public Nullable<decimal> item_Price { get; set; }
        public string item_Name { get; set; }
        public string item_Name2 { get; set; }
        public Nullable<int> item_Index { get; set; }
    }
}
